{
 "title": "Lab dashboards",
 "time": { "from": "2025-11-06T15:11:48.917Z", "to": "2026-01-05T15:11:48.917Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(app36_http_requests_total{status=~\"5..\"}[5m])) / sum(rate(app36_http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app36_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(app36_http_requests_total{status!~\"5..\"}[5m])) / sum(rate(app36_http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}