FROM alpine:3.19
LABEL org.bstu.student.fullname="Filipchuk Dmitriy Vasilevich" \
      org.bstu.student.id="220027" \
      org.bstu.group="АС-63" \
      org.bstu.variant="22" \
      org.bstu.course="RSiOT"
RUN echo "Placeholder image for lab03" > /image-notes.txt
CMD ["cat", "/image-notes.txt"]
